import type { Metadata } from "next";
import "./globals.css";

import { ReactQueryProvider } from "@/app/_utils/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css"
          />
        </head>
        <body>{children}</body>
      </html>
    </ReactQueryProvider>
  );
}
